BASE_URL = "https://www.saucedemo.com"
USER_URL= "https://www.saucedemo.com/inventory.html"
INVALID_LOGIN_XLSX = "data/invalid_login.xlsx"
USERNAME_ID = "user-name"
PASSWORD_ID = "password"
ADD_TO_CART_ID= "add-to-cart-sauce-labs-backpack"
SHOPPING_CART_ID= "shopping_cart_container"
LOGIN_BUTTON_ID = "login-button"
CHECKOUT_ID= "checkout"
LIST_PRODUCT_XPATH= "//*[@id='inventory_container']/div/div/div/div/div/div[2]"
ERROR_MESSAGE_XPATH = "//*[@id='login_button_container']/div/form/div[3]/h3"
USERNAME_PASSWORD_DONT_MATCH = "Epic sadface: Username and password do not match any user in this service"
USER_BLOCK_XPATH="//*[@id='login_button_container']/div/form/div[3]/h3"
USER_BLOCK_DONT_MATCH="Epic sadface: Sorry, this user has been locked out."
USERNANE_REQUIRED_XPATH="//*[@id='login_button_container']/div/form/div[3]/h3"
USERNANE_REQUIRED_DONT_MATCH="Epic sadface: Username is required"
PASSWORD_REQUIRED_XPATH="//*[@id='login_button_container']/div/form/div[3]/h3"
PASSWORD_REQUIRED_DONT_MATCH="Epic sadface: Password is required"
